name: ✨ Feature Request
description: Suggest a completely new feature or enhancement.
title: "[Feature] <A brief summary of your feature suggestion>"
labels: ["enhancement"]
body:
  - type: textarea
    id: problem-description
    attributes:
      label: What problem does this feature solve?
      description: |
        Please provide a clear description of the problem or inconvenience you want to solve with this new feature.
        e.g., I'm always frustrated when... It would be great if there was a feature to...
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: What is your desired solution?
      description: |
        Please describe in detail how the feature you're suggesting should work.
        Where should it appear? How should the user interact with it?
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Have you considered any alternative solutions?
      description: If applicable, describe any other implementations or alternative solutions you've considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context, mockups, or screenshots about the feature request here.
        For example, references to similar features in other apps or modules.
