name: Android CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.gitignore'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.gitignore'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: | 
        ./gradlew assembleRelease
        echo "APK_FILE_ARMEABI=$(find app/build/outputs/apk/release -name 'OPatch_armeabi-v7a_v*.apk')" >> $GITHUB_ENV
        echo "APK_FILE_ARM64=$(find app/build/outputs/apk/release -name 'OPatch_arm64-v8a_v*.apk')" >> $GITHUB_ENV
        echo "APK_FILE_ARMALL=$(find app/build/outputs/apk/release -name 'OPatch_all_v*.apk')" >> $GITHUB_ENV
        echo "APK_FILE_METADATA=$(find app/build/outputs/apk/release -name 'output-metadata.json')" >> $GITHUB_ENV

    - name: Show Artifacts SHA256
      run: |
        echo "### Build Success :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "|ABI|SHA256|" >> $GITHUB_STEP_SUMMARY
        echo "|:--------:|:----------|" >> $GITHUB_STEP_SUMMARY
        armeabi=($(sha256sum "${{ env.APK_FILE_ARMEABI }}"))
        echo "|armeabi|${armeabi[0]}|" >> $GITHUB_STEP_SUMMARY
        arm64=($(sha256sum "${{ env.APK_FILE_ARM64 }}"))
        echo "|arm64|${arm64[0]}|" >> $GITHUB_STEP_SUMMARY
        armAll=($(sha256sum "${{ env.APK_FILE_ARMALL }}"))
        echo "|armAll|${armAll[0]}|" >> $GITHUB_STEP_SUMMARY
        metadata=($(sha256sum "${{ env.APK_FILE_METADATA }}"))
        echo "|metadata|${metadata[0]}|" >> $GITHUB_STEP_SUMMARY

    - name: Upload All APK
      uses: actions/upload-artifact@v4
      with:
        name: OPatch_all_${{ github.event.head_commit.id }}
        path: ${{ env.APK_FILE_ARMALL }}

    - name: Upload Arm64 APK
      uses: actions/upload-artifact@v4
      with:
        name: OPatch_arm64-v8a_${{ github.event.head_commit.id }}
        path: ${{ env.APK_FILE_ARM64 }}

    - name: Upload Armeabi APK
      uses: actions/upload-artifact@v4
      with:
        name: OPatch_armeabi-v7a_${{ github.event.head_commit.id }}
        path: ${{ env.APK_FILE_ARMEABI }}

    - name: Upload Metadata
      uses: actions/upload-artifact@v4
      with:
        name: output-metadata
        path: ${{ env.APK_FILE_METADATA }}
    - name: Upload To Telegram Release
      env:
        COMMIT_MESSAGE: |+
          New push to GitHub\!
          ```
          ${{ github.event.head_commit.message }}
          ```by `${{ github.event.head_commit.author.name }}`
          See commit detail [here](${{ github.event.head_commit.url }})
        COMMIT_URL: ${{ github.event.head_commit.url }}
      run: |
        ESCAPED=`python3 -c 'import json,os,urllib.parse; msg = json.dumps(os.environ["COMMIT_MESSAGE"]); msg = msg.replace(".", "\\."); print(urllib.parse.quote(msg if len(msg) <= 1024 else json.dumps(os.environ["COMMIT_URL"])))'`
        media='[
          {"type":"document", "media":"attach://armeabi"},
          {"type":"document", "media":"attach://arm64"},
          {"type":"document", "media":"attach://armAll"},
          {"type":"document", "media":"attach://metadata", "parse_mode":"MarkdownV2", "caption":"'"${ESCAPED}"'"}
        ]'
        ENCODED_MEDIA=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$media'''))")
        curl -v "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN  }}/sendMediaGroup?chat_id=-1002477655219&media=${ENCODED_MEDIA}" \
         -F armeabi="@${{ env.APK_FILE_ARMEABI }}" \
         -F arm64="@${{ env.APK_FILE_ARM64 }}" \
         -F armAll="@${{ env.APK_FILE_ARMALL }}" \
         -F metadata="@${{ env.APK_FILE_METADATA }}"
