name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload All APKs and output-metadata.json
      id: upload-artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OPatch_all
        path: app/build/outputs/apk/debug/OPatch_all_v*.apk
      if: success() && startsWith(github.event_name, 'push')

    - name: Upload Arm64 APK
      uses: actions/upload-artifact@v3
      with:
        name: OPatch_arm64
        path: app/build/outputs/apk/debug/OPatch_arm64-v8a_v*.apk
      if: success() && startsWith(github.event_name, 'push')

    - name: Upload Armeabi APK
      uses: actions/upload-artifact@v3
      with:
        name: OPatch_armeabi
        path: app/build/outputs/apk/debug/OPatch_armeabi-v7a_v*.apk
      if: success() && startsWith(github.event_name, 'push')

    - name: Upload Metadata
      uses: actions/upload-artifact@v3
      with:
        name: output-metadata
        path: app/build/outputs/apk/debug/output-metadata.json
      if: success() && startsWith(github.event_name, 'push')
